# SPDX-License-Identifier: GPL-3.0-or-later
from __future__ import annotations


class NoopLogger:
    def debug(self, *a, **k): ...

    def info(self, *a, **k): ...

    def warning(self, *a, **k): ...

    def error(self, *a, **k): ...
